---
name: Lint (Container)
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/lint.container.yml
      - Dockerfile

jobs:
  hadolint:
    name: Hadolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: hadolint/hadolint-action@06be81baf89a55ffd0e24b8f04a4185738dd3387 # v3.5.0
        with:
          dockerfile: Dockerfile
