---
name: Lint (YAML)
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths: ["**.ya?ml"]

jobs:
  yamllint:
    name: YAML lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # tag=v3.1.1
        with:
          format: github
