---
name: Lint (Golang)
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/lint.golang.yml
      - go.*
      - cmd/**
      - pkg/**

jobs:
  golangci-lint:
    name: Golang CI lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          # renovate: datasource=golang-version
          go-version: '1.20'
          check-latest: true
      - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4.0.0

      - uses: golangci/golangci-lint-action@3cfe3a4abbb849e10058ce4af15d205b6da42804 # v3.7.1
        with:
          # renovate: datasource=github-releases depName=golangci/golangci-lint
          version: v1.54.2
