---
name: Lint (YAML)
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths: ["**.ya?ml"]

jobs:
  yamllint:
    name: YAML lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # tag=v3.1.1
        with:
          format: github
