---
name: Lint (Golang)
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/lint.golang.yml
      - go.*
      - cmd/**
      - pkg/**

jobs:
  golangci-lint:
    name: Golang CI lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          # renovate: datasource=golang-version
          go-version: '1.22'
          check-latest: true
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: golangci/golangci-lint-action@971e284b6050e8a5849b72094c50ab08da042db8 # v6.1.1
        with:
          # renovate: datasource=github-releases depName=golangci/golangci-lint
          version: v1.56.2
